### ISSUE TITLE
Provide "edition number" in the site index

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#110]
As reported by @RohdeBSH from the IHO S-102 team.

Right now IHO documents in the Metanorma site output is not showing the edition number, causing all editions to look the same.
<img width="486" alt="Screen Shot 2023-01-18 at 4 47 37 PM" src="https://user-images.githubusercontent.com/11865/213150323-d551f1fc-d829-4c37-8c5e-ba9e8a6c5b8f.png">

We should always provide the edition/version number to distinguish multiple editions in the same site.

**Comment by andrew2net** [comment]
@ronaldtse IHO IDs don't have editions. Editions are stored in the `edition` attribute. I think Metanorma should display the `edition`.

**Comment by opoudjis** [comment]
Update RXL template for index of site.

**Comment by opoudjis** [comment]
The template has not been looked at in a very long time: its type is also wrongly rendered. Fixed.

**Comment by opoudjis** [comment]
@andrew2net This issue is awaiting relaton-cli release.

**Comment by andrew2net** [comment]
@opoudjis I didn't get what we need to do here

**Comment by opoudjis** [comment]
I've done an update to the templates folder of relaton-cli, and I won't close this ticket until the next release of relaton-cli. This has waited two years, so it's not urgent.

**Comment by andrew2net** [comment]
@opoudjis released relaton-cli v1.19.3
