### ISSUE TITLE
Support "edition", "version" and "draft"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#12]
From @anermina:
> This document also includes a draft number: 6th edition, draft 2.0.0. Maybe we should add draft number in document attributes?

I think this is best expressed as ":edition: 6, ":version: 2.0.0" and ":draft:", but the "draft" attribute here is most certainly not needed since it isn't a draft.

~~Right now metanorma-iho assumes the "version number" (e.g. "2.0.0") is entered in the ":edition:" attribute, which is probably incorrect.~~ (see clarification below)

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-iho/pull/38#issuecomment-632425840_

**Comment by ronaldtse** [comment]
Asked IHO for clarification:

Some documents have both version and edition:
- S-44 version (2.0.0) edition (6)
- C-17 version (2.0.0) edition (2)
- S-5A version (1.0.2) edition (1)

But some only have edition (which looks eerily like a version number):
- S-102 edition (2.0.0)
- S-63 edition (1.2.1)

For the latter category of documents, are those edition numbers actually version numbers? If so, should we help them fill in an edition number?

**Comment by ronaldtse** [comment]
I have sought clarification from IHO whether this is acceptable:

So all documents are supposed to be “Edition n.n.n”. What should we do for those “editions” that are just “n”?

e.g. for these documents:
- S-44 version (2.0.0) edition (6)
- C-17 version (2.0.0) edition (2)
- S-5A version (1.0.2) edition (1)

Should they be:
- S-44 edition 2.0.0
- C-17 edition 2.0.0
- S-5A edition 1.0.2

(and we drop the old “edition (6)”)

**Comment by opoudjis** [comment]
I don't know how to answer that; I would have thought that edition 6 turns into 6.0.0, but if they're saying that Edition 6 is legacy, and it should be treated as 2.0.0. then that does means we have to drop it. After all, Metanorma is supposed to be an opportunity to streamline SDO processors, and IHO are not advising you to do anything with edition 6.

Which means, @anermina just globally replaces the edition with what has been the draft variable.

There seems to be nothing for me to do here; if you confirm, @ronaldtse, please close this issue.

**Comment by ronaldtse** [comment]
Clarification from IHO: There are these things:

* Edition (`n.0.0`)
* Revision (`n.n.0`)
* Clarification (`n.n.n`)

Relevant documentation from IHO:
https://iho.int/uploads/user/pubs/misc/M3-E-30_03_2020.pdf

<img width="722" alt="Screen Shot 2020-09-02 at 9 08 42 AM" src="https://user-images.githubusercontent.com/11865/91920523-e750cc80-ecfb-11ea-9f4f-e3854e952bcc.png">
<img width="718" alt="Screen Shot 2020-09-02 at 9 08 53 AM" src="https://user-images.githubusercontent.com/11865/91920548-fb94c980-ecfb-11ea-92c2-0b7661965994.png">

<img width="736" alt="Screen Shot 2020-09-02 at 9 08 17 AM" src="https://user-images.githubusercontent.com/11865/91920505-d902b080-ecfb-11ea-9319-d27a89d11455.png">

This means that we should only allow `:edition: x.y.z`. The "S-44 Edition 6" notion is probably a misunderstanding by the PT/WG. 

Question: Should we allow fetching the particular numbers of the `:edition:`? i.e. `:edition-num:` => `x`, `:revision-num:` => `y`, `:clarification-num:` => `z`.

**Comment by opoudjis** [comment]
> Question: Should we allow fetching the particular numbers of the :edition:?

I don't see why. Yes, the number places are meaningful, but what process needs to parse semantic tags, that won't be able to parse the version number? In fact, what process needs to parse version numbers at all? And even if we did, why on earth would they need to be separated in asciidoctor input, when they are not separated in the human-readable presentation?

Do not complicate what does not need to be complicated. Closing this, there is nothing to do here.

**Comment by ronaldtse** [comment]
@opoudjis if we want to keep this truly simple we must disable the attributes for `version` and `revision` in case of confusion.

**Comment by opoudjis** [comment]
... Agreed, reopening.

**Comment by opoudjis** [comment]
Nothing to do here: it turns out :version: and :revision: are not natively supported in Metanorma. We should retain :draft: just in case people want to track iterations of prepublished clarifiications; but they will not turn up in document rendering.
