### ISSUE TITLE
Annex wrongly numbered in Metanorma-IHO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#13]
In C-17, reported by @manuel489 and @anermina:

> "Annex I" renders as "Annex J" in generated document. @anermina could you confirm this when you can, please?

Yes, I also noticed this. However, IHO is in alpha phase, so I didn't report it as an issue now. Source .adoc is correct here.

_Originally posted by @anermina in https://github.com/metanorma/mn-samples-iho/issues/44#issuecomment-632325666_

**Comment by opoudjis** [comment]
This is deliberate: "Annex I" is renamed to "Annex J", so as to prevent confusion with roman numeral I. This has been taken from ITU. It is not being done in IHO, clearly; but I'm not convinced it shouldn't be. @ronaldtse?

**Comment by ronaldtse** [comment]
@opoudjis 

1. Can we document the "Annex I" is renamed to "Annex J" behavior in metanorma.com for ITU?

2. I will ask IHO

**Comment by ronaldtse** [comment]
Sought clarification from IHO.

**Comment by opoudjis** [comment]
Unassigning myself. If you get a response from IHO, Ronald, reassign to me.

**Comment by opoudjis** [comment]
There are only 3 annexes in present version. Jeff not concerned either way, nobody considered Annex I ambiguous. Revert behaviour.
