### ISSUE TITLE
Duplicated footnote rendering behavior

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#14]
As reported by @manuel489 and @anermina on C-17:

> Footnote 10 (footnote:[http://inspire.ec.europa.eu/]) is not shown in generated version. At least not on the page where it is referenced. Such footnote is duplicated with footnote 1 in .adoc source, so it gets referenced with footnote number 1.

> This actually regularly happens when footnote is repeated. At least I saw this in other generated documents as well, while some of the originals duplicate the footnote assigning it a different number, so it can appear on the page where that footnote is set. I'm not sure which rule does IHO want to apply for the footnotes.

We will need a consistent behavior for this, I think the best solution right now is to create only a single footnote, and refer back to that footnote. The footnote should only be displayed once at the first footnote instance.

_Originally posted by @anermina in https://github.com/metanorma/mn-samples-iho/issues/44#issuecomment-632325666_

**Comment by anermina** [comment]
> We will need a consistent behavior for this, I think the best solution right now is to create only a single footnote, and refer back to that footnote. The footnote should only be displayed once at the first footnote instance.

That behavior is applied in IHO. I honestly don't remember seeing and generated document which behaves differently. Only some original documents do, like in this case.

**Comment by manuel489** [comment]
> > We will need a consistent behavior for this, I think the best solution right now is to create only a single footnote, and refer back to that footnote. The footnote should only be displayed once at the first footnote instance.
> 
> That behavior is applied in IHO. I honestly don't remember seeing and generated document which behaves differently. Only some original documents do, like in this case.

I agree with @anermina, that is indeed the behavior applied, and the reason why I reported it as an issue. Because, if that is the case, the user would need to go back to the page where the first footnote instance is, instead of seeing it right at the bottom on the page where it is instantiated for second time.

**Comment by ronaldtse** [comment]
> Because, if that is the case, the user would need to go back to the page where the first footnote instance is, instead of seeing it right at the bottom on the page where it is instantiated for second time.

I think this is acceptable. Consider the case where the later page contains footnote 1 and 4, then both footnotes 1 and 4 are rendered at the bottom, which will look strange.

**Comment by manuel489** [comment]
> > Because, if that is the case, the user would need to go back to the page where the first footnote instance is, instead of seeing it right at the bottom on the page where it is instantiated for second time.
> 
> I think this is acceptable. Consider the case where the later page contains footnote 1 and 4, then both footnotes 1 and 4 are rendered at the bottom, which will look strange.

Well, yeah, it will look strange if the footnote numbering is maintained. But I think wouldn't look that strange if the repeated footnotes follow with the numbering cadence, i.e. with different reference numbers, like a new footnote. (Just like it is achieved in the original source.)

However, I realize some other cumbersome situations can raise from that approach, specially if we consider the HTML output. So, I agree with you. Thanks!

**Comment by opoudjis** [comment]
So... what am I doing? I can make the behaviour vary from document to document, and the behaviour of the repeated footnote not being renumbered is in fact unusual (although standards seem to like it). But I don't have a decision here. And since IHO in general does not have consistent editorial policy, I suggest we stick with the Metanorma default, which currently is not to renumber repeated footnotes.

**Comment by ronaldtse** [comment]
@opoudjis I agree with your suggestion, there's nothing to be done here. Thanks!

**Comment by ronaldtse** [comment]
BUT -- can we document this as a feature on metanorma.com?
