### ISSUE TITLE
(URGENT) Unable to utilize Relaton-IHO edition number to fetch S-100

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#143]
Relaton-IHO has recently added edition number fetching in https://github.com/relaton/relaton-iho/issues/16.

Relaton-IHO by itself works:

```sh
$ bundle exec relaton fetch "IHO S-100 5.0.0"
<bibdata type="standard" schema-version="v1.2.3">
  <fetched>2023-04-11</fetched>
  <title type="main" format="text/plain" language="en">IHO Universal Hydrographic Data Model</title>
  <title type="main" format="text/plain" language="fr">Modèle universel de données hydrographiques de l’OHI</title>
  <uri type="pdf">https://iho.int/uploads/user/pubs/standards/s-100/S-100_5.0.0_Final_Clean_Web.pdf</uri>
  <docidentifier type="IHO" primary="true">S-100</docidentifier>
  <docnumber>100</docnumber>
  <date type="published">
    <from>2022-12-01</from>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>International Hydrographic Organization</name>
      <abbreviation>IHO</abbreviation>
      <uri>www.iho.int</uri>
    </organization>
  </contributor>
  <edition>5.0.0</edition>
  <version>
    <revision-date>2022-12-01</revision-date>
  </version>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
  <status>
    <stage>in-force</stage>
  </status>
  <copyright>
    <from>2022</from>
    <owner>
      <organization>
        <name>International Hydrographic Organization</name>
        <abbreviation>IHO</abbreviation>
        <uri>www.iho.int</uri>
      </organization>
    </owner>
  </copyright>
  <series type="main">
    <title type="original" format="text/plain">
      <variant language="en" script="Latn">Standards and Specifications</variant>
      <variant language="fr" script="Latn">Normes et Spécifications</variant>
    </title>
    <place>Monaco</place>
    <organization>International Hydrographic Organization</organization>
    <number>S</number>
  </series>
  <place>Monaco</place>
  <validity>
    <validityBegins>2022-12-01 00:00</validityBegins>
  </validity>
  <ext schema-version="v1.0.0">
    <editorialgroup>
      <committee>
        <name>Hydrographic Services and Standards Committee</name>
        <abbreviation>HSSC</abbreviation>
        <workgroup>
          <name>S-100 Working Group</name>
          <abbreviation>S-100WG</abbreviation>
        </workgroup>
      </committee>
    </editorialgroup>
  </ext>
</bibdata>
```

This is the item added in https://github.com/relaton/relaton-data-iho/commit/e7189f65778ce3595423c3ae2ee3e7e1302f740b.

However, when I use it in Metanorma:

```adoc
[bibliography]
=== References
* [[[iho-s100,IHO S-100 5.0.0]]]
...
```

It gives this message:
```
[relaton-iho] ("IHO S-100 5.0.0") fetching...
[relaton-iho] ("IHO S-100 5.0.0") found S-100
```

<img width="519" alt="Screenshot 2023-04-11 at 9 21 08 AM" src="https://user-images.githubusercontent.com/11865/231030717-ca67d788-9534-4d77-9603-88bdf661408b.png">

This means Metanorma-IHO is doing something funny with the publication identifiers instead of faithfully delegating them to Relaton. It should not.

This is blocking https://github.com/iho-ohi/S-102-Product-Specification/pull/24 .

**Comment by hasel001** [comment]
I made the change as @ronaldtse suggested. In the artifacts generated about 12 hours ago, two major issues exist:

1. The PDF has only a blank line after the bracketed "1" where the S-100 reference should be.
2. There is no Word document in the artifacts at all.

Let me know if you need me to change/try something else. Thanks!

**Comment by hasel001** [comment]
@ronaldtse No worries. Because there were a few references whose version needed updating, I already completed the changes manually post-Metanorma and delivered our v2.2.0 to our parent working group. We really appreciate your help!

**Comment by ronaldtse** [comment]
Thanks @hasel001 !

I'm not entirely sure why, perhaps it was due to caching, but I just tried again and the "S-100 5.0.0" document does show up in the bibliography (PDF):

<img width="521" alt="Screenshot 2023-04-11 at 9 55 33 PM" src="https://user-images.githubusercontent.com/11865/231185808-25829c2b-b3d4-4006-b09d-a2e1e77c868e.png">

Word:
<img width="472" alt="Screenshot 2023-04-11 at 9 56 17 PM" src="https://user-images.githubusercontent.com/11865/231186044-b938afe5-90e2-46fd-99a1-a09066041dc9.png">

@opoudjis can you help verify that this is no longer an issue and that it can be closed? Thanks.
