### ISSUE TITLE
Word + HTML: minimize figure margin like PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#156]
As requested by @rohdebsh here:
* https://github.com/iho-ohi/S-102-Product-Specification/issues/38#issuecomment-1538730267

This is a comparison of the PDF vs Word output of S-102 Figure 2:
<img width="1212" alt="Screenshot 2023-05-09 at 1 00 07 AM" src="https://user-images.githubusercontent.com/11865/236885024-e8872814-75a2-4a07-8feb-4d5ba0da56e8.png">

Here, the size difference lies in the styling of the Metanorma Word vs Metanorma PDF:
* In Word, the is a figure margin based on page width
* In PDF, there is no figure margin compared to page width

The PDF treatment of Figure is desired here by IHO.

This task is to remove / minimize the figure margin in Word and HTML.

**Comment by opoudjis** [comment]
> In Word, the is a figure margin based on page width

That is inaccurate. There is a precalculated maximum figure size, based on *A* page width, and there are no margins applied. The issue appears rather to be that the page width used in the calculations is a one-size fits all page width, and it is not necessarily a match to the current document; so I need to be able to parse the CSS of the given Word document, to discover its current page width.

**Comment by opoudjis** [comment]
Fix doesn't currently deal with landscape (neither did previous solution), and we're grabbing the first found of `@page WordSection2`,  `@page WordSection3`, `@page`.

**Comment by opoudjis** [comment]
<img width="1198" alt="Screenshot 2023-05-19 at 01 29 43" src="https://github.com/metanorma/metanorma-iho/assets/1911039/825c3a9b-4e3e-4504-bc02-c88943d8c76d">
