### ISSUE TITLE
(URGENT, PDF) Copyright statement broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#184]
<img width="745" alt="Screenshot 2023-11-04 at 5 06 12 PM" src="https://github.com/metanorma/metanorma-iho/assets/11865/482d020e-ee63-4d60-958b-1bfdcd0ac73c">

Document:
* https://github.com/iho-ohi/S-102-Product-Specification

@Intelligent2013 please help check if this affects other flavors as well.

**Comment by Intelligent2013** [comment]
@ronaldtse the presentation XML contains 
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/2f69967f-9b13-4bc0-b7f0-cc2c2d3f3b1f)

```xml
  <boilerplate>
    <clause id="_copyright_statement" obligation="normative">
      <title depth="1">copyright-statement&#x3e;</title>
      <clause id="_d4f42e72-b8a5-ac36-c140-bd0d9d6e1fa4" obligation="normative">
        <p id="_45c1c270-f7bb-c17b-6a7a-b4cc945a36e2" align="center">© Copyright International Hydrographic Organization 2023</p>
```


The source in the https://github.com/metanorma/metanorma-iho/blob/main/lib/metanorma/iho/boilerplate.adoc:

https://github.com/metanorma/metanorma-iho/blob/41b6296f975ccca1f70e1837c13b6d868dd0444f/lib/metanorma/iho/boilerplate.adoc?plain=1#L1

ping @opoudjis

**Comment by Intelligent2013** [comment]
@opoudjis thank you for the update.

Fixed:
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/2d138fac-af4a-4a98-a6a8-e1100c50cbd5)

**Comment by ronaldtse** [comment]
Thanks! Please close when done.
