### ISSUE TITLE
(URGENT, PDF) Table cell text out of bounds

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#185]
<img width="728" alt="Screenshot 2023-11-04 at 5 10 11 PM" src="https://github.com/metanorma/metanorma-iho/assets/11865/a267ebfa-4c24-4449-b91e-801cb2c35366">

Document:
* https://github.com/iho-ohi/S-102-Product-Specification/

**Comment by Intelligent2013** [comment]
@ronaldtse the repository https://github.com/iho-ohi/S-102-Product-Specification/ contains another table (the document edition is `2.2.0`):
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/220884ef-b42f-4663-aa49-4aafe8b1e728)
...
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/75735852-0f14-42b6-8375-7bcafacdd39e)

I've found the version `2.1.0` in https://github.com/metanorma/mn-samples-iho/tree/main/sources/s102 and repeated the issue.
The issue occurs due the long text in the cells below:
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/f8f7fb14-66be-46b3-8e69-9169e2e8f2b8)

I propose to set the landscape mode by enclosing the table into
```adoc
[%landscape]
<<<

[[discoverymetadablock-class-attributes]]
.S102_DiscoveryMetadataBlock class attributes
...

[%portrait]
<<<
```

Then PDF renders so:
![image](https://github.com/metanorma/metanorma-iho/assets/5559926/55a9cb08-c52b-48be-aea2-70776de48e15)
