### ISSUE TITLE
IHO resolution 2/2007 PRINCIPLES AND PROCEDURES FOR MAKING CHANGES TO IHO TECHNICAL STANDARDS AND SPECIFICATIONS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#2]
1. Scope

1.1 These principles and procedures are intended to be applied to all proposals for changes to IHO technical standards and for new work items that will require significant resources to resolve or will potentially impact on those who need to apply the standards. They are not intended for IHO publications, catalogues or supporting documentation of a guidance, general or non-technical nature.

1.2 Any reference to “standards” in these principles and procedures follows the ISO/IEC definitions for standard and guide and may therefore also include some IHO “specifications” and “guidelines” as appropriate . IHO Product Specifications are considered to be standards. A list of IHO technical standards that should follow the processes described in this Resolution is provided as Appendix 1 to this Resolution.

2. Principles

2.1 Improvements to technical standards can only occur by change. However, significant change can lead to problems such as incompatibility between systems, high updating costs, market monopoly, dissatisfied users, or increased risks to safety of navigation. The following guiding principles have been developed to avoid these circumstances.

2.1.1 Before approval is granted, any proposed changes to existing standards should be assessed from a technical and commercial perspective, also taking into account any other relevant factors.

2.1.2 Where possible, assessment should involve not only IHO Member States through the Council but all relevant parties such as international organisations, maritime administrations, equipment manufacturers, data distributors, users and other professional organisations. These are the stakeholders.

2.1.3 As far as practicable, any change to standards or systems should be “backwards compatible”, or the existing version must be supported for a specified time.

2.1.4 If changes are required for the basis of product enhancement rather than for safety of navigation, then the previously approved system must be allowed to continue to be used at sea for a sufficient time to allow changes to be implemented on board.

2.1.5 If not already specified by an external or higher IHO authority, the timeline for making changes should be defined, where appropriate.

2.1.6 In exceptional cases (for example, those affecting safety of navigation), it may be necessary to make recommendations for immediate change to standards and systems to the relevant authorities. This may be achieved through shortening the normal time frames for submission and consideration of proposals.

2.1.7 The principles of a recognized project management system should be followed.

2.1.8 All interested parties should be encouraged to continuously improve IHO technical standards. Constructive feedback should therefore be provided for all rejected proposals.

3. Procedures - General

3.1 Standardised procedures help to ensure that any proposed changes to IHO standards are properly assessed and implemented. These procedures should remain simple to encourage their use.

3.2 The following diagram illustrates the typical life cycle of an IHO standard:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/11865/77985422-0612f780-7347-11ea-9bc3-9eb8287c0c3a.png">

3.2.1 Changes to IHO standards are classified at one of three different levels: new edition, revision, or clarification (see paragraph. 5.1). In each case, the development, consultation and approval process will be slightly different, ranging from a very comprehensive regime for new editions, to approval at the level of a subordinate body for clarifications. New editions and revisions are considered to be “significant changes” for the purposes of review, consultation and approval.

3.2.2 The relevant Committee (HSSC or IRCC) should consider all proposals to develop new editions and revisions to standards before work begins.

- The Committee should consider the impact on relevant stakeholders when assessing a proposal and planning any subsequent work. This assessment should systematically include a risk and feasibility analysis, and an estimate of the resources needed for the implementation of a new or revised standard or its development, including within Member States Hydrographic Services.

- If rejected, feedback should be provided to the proposal originator giving the reasons for rejection.

3.2.3 After the Committee has endorsed proposals and established a work priority, the IHO Secretariat will incorporate tasks into the relevant work programmes.

3.2.4 Relevant stakeholders should be notified by the IHO Secretariat of the timetable for new work items and be invited to comment and participate as appropriate. The notification should include a summary forecast of:

- the potential changes,

- the documents affected,

- the likely action list for relevant stakeholders,

- the timetable for implementation, and

- the proposed effective date of the new or revised standard.

3.2.5 The IHO Secretariat should maintain an on-line register of IHO stakeholders. The register should be used to inform and seek input from stakeholders concerning any proposed changes to IHO standards.

3.2.6 The relevant subordinate bodies should provide the Committee with progress reports on a regular basis and after each milestone during the development and testing phases. These should be made available to stakeholders by the IHO Secretariat.

3.2.7 At the successful completion of the development and testing phases for new standards and proposed changes to existing standards, the Committee should review the work done in terms of its impact on relevant stakeholders and whether the appropriate non-IHO stakeholder consultation process has been achieved.

3.2.8 After endorsement by the Committee and the Council, the new or changed standard should be submitted to Member States by the IHO Secretariat for approval of the content, and confirmation of the “effective date”.

3.2.9 At the “effective date”, the new or changed standard becomes the effective standard. A “superseded” standard should normally remain available concurrently with the revised standard for a suitable transition period.

3.2.10 A “superseded” standard may be “retired” as an available standard when it is no longer appropriate for use, subject to the approval of the Member States through the Council.

3.2.11 Subordinate bodies may assess and authorise clarifications to standards and associated references, subject to seeking input from relevant stakeholders.

4. Urgent Revisions

4.1 The introduction of revisions to existing standards is intentionally a thorough process, in order to allow for appropriate levels of development, testing and consultation. However, there may be instances where more urgent action is required, especially where there are serious implications to safety of navigation. In such cases, a “fast- track” approval and implementation process may be needed. This should only occur in exceptional circumstances and in consultation with Member States through the Council. Any such fast-tracked revisions still require the approval of Member States before they can enter into force.

5. Procedures - Specific

5.1 New Editions, Revisions and Clarifications

New Edition

New Editions of standards introduce significant changes. New Editions enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types, to be introduced. New Editions are likely to have a significant impact on either existing users or future users of the revised standard. It follows that a full consultative process that provides an opportunity for input from as many stakeholders as possible is required. Proposed changes to a standard should be evaluated and tested wherever practicable. The approval of Member States is required before any New Edition of a standard can enter into force. All cumulative clarifications and revisions must be included with the release of an approved New Edition of a standard.

Revision

Revisions are defined as substantive semantic changes to a standard. Typically, revisions change existing specifications to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances; or add new specifications within an existing section. Revisions could have an impact on either existing users or future users of a revised standard. It follows that a full consultative process that provides an opportunity for input from as many stakeholders as possible is required. Proposed changes to a standard should be evaluated and tested wherever practicable. The approval of Member States is required before any revisions to a standard can enter into force. All cumulative clarifications must be included with the release of approved corrections revisions.

A revision shall not be classified as a clarification in order to bypass the appropriate consultation processes.

Clarification

Clarifications are non-substantive changes to a standard. Typically, clarifications: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A clarification must not cause any substantive semantic change to a standard. Clarifications are the responsibility of the relevant subordinate body and may be delegated to the responsible editor.

5.2 The associated version control numbering to identify changes (n) to IHO standards should be as follows:

New Editions denoted as n.0.0 

Revisions denoted as n.n.0 

Clarifications denoted as n.n.n

5.3 The following diagram illustrates the development, consultation and approval processes for IHO standards:

<img width="523" alt="Screen Shot 2020-03-31 at 11 57 54 AM" src="https://user-images.githubusercontent.com/11865/77985381-eb408300-7346-11ea-8aa2-7b89285ec1ff.png">

**Comment by ronaldtse** [comment]
Some more reading...

**Comment by opoudjis** [comment]
I don't see how any of this impacts on the documents. At most, we might need to indicate the document that this document has been superseded by during the transition period; but that is already supported in the schema as `:superseded-by:`. The versioning is already addressed in https://github.com/metanorma/metanorma-iho/issues/12
