### ISSUE TITLE
Query on IHO boilerplate inconsistencies

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iho#24]
Originally from https://github.com/metanorma/mn-samples-iho/issues/35

At first I thought copyright was written by our team (and is incomplete due to the alpha phase of IHO conversion), but then I realized by comparing copyrights from other documents with the ones provided in original and generated B12 that it is "incomplete" in the original documents as well. 
Below are the copyright differences which were noticed in B12, but in case this copyright was provided by IHO and should remain as-is, please ignore these comments.

- Copyright: 2nd paragraph. "IHO Secretatiat" in the original vs. "IHO" in generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/82149006-019e9180-9856-11ea-8636-dbaf8a3977b8.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82148998-f8adc000-9855-11ea-91ac-e9a08237f9a9.png)

- Copyright: first two paragraphs. Some commas are missing in generated document. Missing ones are yellow highlighted in the original document (image below).

Original:
![image](https://user-images.githubusercontent.com/55683568/82152455-893dcd80-9861-11ea-9ea6-30b63562d97e.png)

- Copyright: 4th and 5th paragraph. "IHO Secretariat" in original vs. "International Hydrographic Organization (IHO) Secretariat" in generated document (yellow highlighted).

Since IHO conversion is in alpha stage, I just underlined (red) terms in generated document which should be replaced with specific names. However, I believe "source version of [name] in" should currently be written as "source version of IHO [document/publication] [name] in" (blue underlined in the original document). Moreover, it seems "translation of IHO [document/publication] [name]" should be written as "translation of IHO [nameFull]" (blue and black underlined in the original document). `nameFull` would be a full name of publication/document in this case.

Original:
![image](https://user-images.githubusercontent.com/55683568/82149840-9b1a7300-9857-11ea-8246-521d22a8ab3f.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82153875-7b407a80-986a-11ea-837c-7a341b8df42f.png)

- Copyright: last paragraph. "IHO Secretariat" in original vs. "IHO" in generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/82150309-8b4f5e80-9858-11ea-8643-087718c507cc.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82150313-93a79980-9858-11ea-9803-3bfcb441a167.png)

**Comment by opoudjis** [comment]
To be addressed by Yong Baek providing latest copyright statement.

**Comment by JeffWootton** [comment]
Lates version of the IHO Copyright note as included inn the latest published IHO Publicstions:

[IHO Copyright Note.docx](https://github.com/user-attachments/files/17559325/IHO.Copyright.Note.docx)
