### ISSUE TITLE
Implement desired IHO citation format (of IHO documents and other documents)

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iho#25]
Implement https://github.com/metanorma/metanorma-iho/issues/5 for PDF

**Comment by Intelligent2013** [comment]
@opoudjis How to determine IHO and non-IHO documents?

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe you can determine from the Relaton data. @andrew2net can you help? Thanks.

**Comment by andrew2net** [comment]
@Intelligent2013 there are `docidentifier` elements. A type of the first of them is type of the document:
```xml
<bibdata type="standard">
  <fetched>2020-03-29</fetched>
  <title type="main" format="text/plain" language="en">IHO-IOC GEBCO Cook Book</title>
  <title type="main" format="text/plain" language="fr">Livre de recettes GEBCO OHI-COI</title>
  <uri type="pdf">https://www.star.nesdis.noaa.gov/socd/lsa/GEBCO_Cookbook/documents/CookBook_20191031.pdf</uri>
  <docidentifier type="IHO">B-11</docidentifier>
...
```

> I can't generate IHO xmls due error https://github.com/metanorma/mn-samples-iho/runs/1066337877)

You need to upgrade the relaton-iho to version 1.3.2

**Comment by Intelligent2013** [comment]
Done:
![изображение](https://user-images.githubusercontent.com/5559926/92496713-294ca780-f201-11ea-8bac-04602838905e.png)
