### ISSUE TITLE
IHO document stages as relating to Resolution 2/2007

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#3]
![iho-document-stages](https://user-images.githubusercontent.com/11865/77987224-da464080-734b-11ea-8a5e-9f8ea5fce50a.png)

**Comment by ronaldtse** [comment]
@opoudjis for you to "look" at.

**Comment by opoudjis** [comment]
Merging into https://github.com/metanorma/metanorma-iho/issues/6
