### ISSUE TITLE
Fontist licensing breakage

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iho#44]
All other gems are passing fine in their fontist licensing under GitHub Actions. IHO alone is not, and it is unpredictable: different runs give different behaviour; I've had a run where only one Mac instance failed, and I've rerun to find multiple instances fail.

https://github.com/metanorma/metanorma-iho/runs/1680413257?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Fixed by https://github.com/metanorma/metanorma-iho/commit/186514f398d679c92d3a0860f4a8e3aa4178d574

Now we skip font installation in all metanorma's processors
