### ISSUE TITLE
Implement Metanorma-IHO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#6]
For the International Hydrographic Organization.

Model confirmed here: https://github.com/metanorma/metanorma-model-iho
Samples available here: https://github.com/metanorma/mn-samples-iho

**Comment by opoudjis** [comment]
And stage model (Presumably) is this:


![](https://user-images.githubusercontent.com/11865/77987224-da464080-734b-11ea-8a5e-9f8ea5fce50a.png)

**Comment by ronaldtse** [comment]
Yes.

**Comment by opoudjis** [comment]
The model is saying that both

* annex and appendix are permissible names of supplementary material. (On investigation, it appears that appendixes are informative annexes, as in ITU.)
* and that annexes can contain appendices, as in ISO.

Logically, that means that appendices can contain appendices too. That doesn't sound plausible  me, but I'm implementing what's given to me...

**Comment by opoudjis** [comment]
Done all of model.

**Comment by ronaldtse** [comment]
> Logically, that means that appendices can contain appendices too. That doesn't sound plausible me, but I'm implementing what's given to me...

I do not know whether appendices can have appendices, it would be unlikely...

**Comment by ronaldtse** [comment]
> I do not know whether appendices can have appendices, it would be unlikely...

Sought clarification from IHO, IHO is now investigating...

**Comment by opoudjis** [comment]
The diversity of coverpages in IHO is... unsustainable. Until told otherwise, I am going to use the B-12 coverpage only.

Source code is being rendered in body text font, Cambria, which is... ill-advised, but I'm keeping for now.

**Comment by opoudjis** [comment]
There is very little consistency in rendering across the range of sample documents. 

* Heading numbers: 2., 2.1. vs 2., 2.1
* Body fonts: Arial, Times, Cambria
* Figure numbering: restarting per chapter (12-1), sequential (e..g 6 in chapter 12)
* Page numbering: left bottom, centre bottom, top left
* Header/Footer usage to give title and identifier: usually not, sometimes yes
* Index of Figures and Tables: Sometimes
* Abbreviations: unnumbered section in preface; section 1.3.3; annex A; named Glossary or Abbreviations or List of Acronyms
* Terms & definitions: section 1.3,  section 3
* References: none, section 1.2, section 1.3, section 3.1

... it is already clear, I understand, to IHO, but: we will need to pick one of these options in each case, and we can't support all of them. 

Is there an exemplar among all these documents of what IHO want their documents to look like?

**Comment by ronaldtse** [comment]
> Is there an exemplar among all these documents of what IHO want their documents to look like?

Yes, those are the B-12 and S-102 documents (mostly). The purpose of the work is to place all the documents in the same structure. We will have to work out the exact requirements.

**Comment by opoudjis** [comment]
First cut done.
