### ISSUE TITLE
PDF: Extend spacing in the ToC

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iho#72]
Spacing between the clause number and its name on the third level of the ToC needs to be extended because numbers currently overlap with the titles.

Example:
![image](https://user-images.githubusercontent.com/55683568/198896834-c1708232-b2dc-4fca-8198-ea4a1dec38c8.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 I think the IHO layouts need some updating and clean up to the latest best practices. Thanks!

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/202000146-0bccd42c-8eb8-4b66-ab95-4cdbed71cb9f.png)
