### ISSUE TITLE
PDF: Tables in IHO S102 are too wide to fit

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iho#73]
Is it possible to reduce the font size in tables that include very wide cells? For example, manual manipulation of cell width in the table "S102_DiscoveryMetadataBlock class attributes" from IHO S102 cannot solve the issue because several cells in the row include long sequences of characters that cannot be broken into another row.

![image](https://user-images.githubusercontent.com/55683568/198900791-d52a36ed-20db-4ebd-b0d3-0bc48e53c840.png)

**Comment by opoudjis** [comment]
This is an issue that impacts Word as well as PDF, and it's not going to go away with kludges like this.

The real solution, I suggest, is landscape tables: https://www.metanorma.org/author/topics/document-format/text/#page-breaks . I was going to add, soft hyphenation, but soft hyphenation is not going to work here.

We don't support smaller fonts in Metanorma at this time, and given how prescriptive SDOs are about font size, I'd really be reluctant to, even in an "in case of emergency" case like this.

**Comment by Intelligent2013** [comment]
I've set the font-size for tables in IHO XSLT as in source PDF. After that, PDF looks better, but isn't good:

![image](https://user-images.githubusercontent.com/5559926/202001904-a482e740-7838-4bab-8a49-c9c93ea15b23.png)

This table in the original PDF has non-standard width:

![image](https://user-images.githubusercontent.com/5559926/202002313-80e82725-2c5e-48c9-b198-e4fe3f5b0b73.png)

In Adoc we can set the table width via attribute `width="105%"`:
```asciidoc
[[discoverymetadablock-class-attributes]]
.DiscoveryMetadataBlock class attributes
[cols="a,a,a,a,a,a",options="header",width="105%"]
```

After that, the resulted PDF looks ok:

![image](https://user-images.githubusercontent.com/5559926/202002888-459f515a-33c5-412e-b8bf-9b2c1f69d76d.png)
![image](https://user-images.githubusercontent.com/5559926/202002962-76234788-0b23-4a32-ae32-0b3b542817bd.png)
