### ISSUE TITLE
IHO S-102: Naming conventions - Clauses, Chapters and Sections

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iho#76]
IHO S-102 uses the term Section for the first level, and Clause for lower levels. Metanorma currently uses the term Chapter for the first level and Section for lower levels.

The original is on the left and the generated file is on the right.
![image](https://user-images.githubusercontent.com/55683568/199106918-e239fe4c-915b-490f-984f-b0300696a86a.png)
![image](https://user-images.githubusercontent.com/55683568/199107196-15cc4203-60af-4c66-a8b6-59c76f5ca5e6.png)
![image](https://user-images.githubusercontent.com/55683568/199107738-4b0502d7-75c4-46b0-a9b3-ee7c1bfc8342.png)

**Comment by opoudjis** [comment]
https://iho.int/uploads/user/pubs/standards/S-98/S-98%20Main_Ed%201.0.0_Final.pdf , done May 2022, is consistent with S-102 in using section for lower levels, and numbering tables by clause.

https://iho.int/uploads/user/pubs/standards/s-44/S-44_Edition_6.1.0.pdf , also done October 2022, does Section for lower levels, and numbers tables consecutively.

https://iho.int/uploads/user/pubs/standards/s-58/S-58%20Ed%207.0.0_Final.pdf, also done October 2022, uses Section for first level, and part (!!!) for lower levels.

@ronaldtse As far as I can see, there is no consistency in current IHO usage, and I am not going to change anything in the rendering without a coherent statement of what is to be done from IHO.

**Comment by opoudjis** [comment]
Go with S-102 as exemplar.
