### ISSUE TITLE
IHO S-102: Naming convention for Figures and Tables

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iho#77]
IHO S-102 names figures in the format `Figure <clause number>-<number of the figure in the clause>`. Analogy applies to the tables.

The original is on the left and the generated file is on the right.
![image](https://user-images.githubusercontent.com/55683568/199108262-f50659bd-60f7-4ddb-a680-1cfb29f98860.png)
![image](https://user-images.githubusercontent.com/55683568/199108420-7be54beb-6108-4224-90ef-653ac01cf54d.png)

**Comment by opoudjis** [comment]
As with https://github.com/metanorma/metanorma-iho/issues/76 , not actioning until there is a coherent statement from IHO as to when to use which convention. Note that IEEE and ITU allow this as an option per document, `:hierarchical-object-numbering:`

**Comment by opoudjis** [comment]
Align with S-102 as the reference format: have hierarchical numbering of tables and figures.

**Comment by opoudjis** [comment]
Informative annexes are numbered with Arabic numbers: Annex 1. But that means that clauses in the main section and informative annexes are not currently differentiated: See 1.1 could be an annex or a main clause: I need to prefix "Annex" throughout.
