### ISSUE TITLE
IHO: Reference layout

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iho#88]
Source: https://github.com/metanorma/metanorma-iho/issues/74#issuecomment-1318193430

Need clarification from IHO.
What PDF should be used as reference for PDF/DOC/HTML layout updates?

- https://iho.int/uploads/user/pubs/standards/s-57/S-57%20Appendix%20B.1%20Annex%20A_UOC_Ed%204.3.0_Final.pdf

- https://iho.int/uploads/user/pubs/standards/s-58/S-58%20Ed%207.0.0_Final.pdf

- https://iho.int/uploads/user/pubs/standards/S-98/S-98%20Main_Ed%201.0.0_Final.pdf

- https://iho.int/uploads/user/pubs/standards/s-99/S-99%20Ed%202.0.0_Final.pdf, https://github.com/metanorma/mn-samples-iho/files/9867494/s-102.pdf

These PDF have difference ToC styles, page margin, font-sizes, clause's numbering format, etc.

Related questions:
- https://github.com/metanorma/metanorma-iho/issues/75
- https://github.com/metanorma/metanorma-iho/issues/76
- https://github.com/metanorma/metanorma-iho/issues/77

Currently, IHO XSLT adapted for compliance PDF with S-102.

**Comment by opoudjis** [comment]
Intention is to align to one format ultimately, and any changes will need to be on request. S-102 is the only project up and running. C-17 and S-158 are the two future potential projects, both of which should use S-102 format, but that is still to be confirmed.

We will not go back to the previous formats. S-158 may raise its own format concerns; if it does, that will constitute a new ticket.
