### ISSUE TITLE
HTML: lists inside tables protruding out of table cells at the left

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#9]
As seen in this document:
https://metanorma.github.io/mn-samples-iho/documents/s5b.html

<img width="464" alt="Screen Shot 2020-05-14 at 6 49 20 PM" src="https://user-images.githubusercontent.com/11865/81925839-a0877b80-9613-11ea-8ab4-29b85667a760.png">

**Comment by opoudjis** [comment]
Table cells are set to 0 padding in code; this is overridden in ISO and inheriting flavours' HTML SCSS, but not elsewhere. The 0 padding does not seem justified for HTML, and will lead to such issues elsewhere; dropping it in HTML tables.
